export const calc = {
    "decimal": ".",
    "zero": "0",
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "add": "+",
    "subtract": "-",
    "multiply": "*",
    "divide": "/",
    "clear": "Clear",
    "erase": "E",
    "equals": "="
}

export const calcReverse = {
    ".": "decimal",
    "0": "zero",
    "1": "one",
    "2": "two",
    "3": "three",
    "4": "four",
    "5": "five",
    "6": "six",
    "7": "seven",
    "8": "eight",
    "9": "nine",
    "=": "Enter",
    "E": "Backspace",
    "Clear": "C",
    "+": "add",
    "-": "subtract",
    "*": "multiply",
    "/": "divide"
}